# Generated by Django 4.2.2 on 2023-06-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_core_guestbook_delete_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='first_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='guestbook',
            old_name='user_message',
            new_name='book_name',
        ),
    ]
